language: go
go:
  - 1.11.5

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"

install:
  - dep ensure

matrix:
  include:
    - language: node_js
      node_js:
        - "10"

script: npm ci && make deploy

notifications:
  email: false
