language: go
go:
  - 1.11.5
install:
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"

matrix:
  include:
    - language: node_js
      node_js:
        - "10"

script: npm ci && make deploy

notifications:
  email: false
